version: '3.7'
services:
  web:
    image: applet-library/abouerp:latest
    networks:
      - library
    ports:
      - 9998:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/resources/application.yml:/app/resources/application.yml:ro
      - /root/web/storage/Library:/Library
    restart: always

networks:
  library:
    external: true





